name: "Rebuild image and push to dockerhub"

on:
  push:
    branches: 
      - main
    paths:
      - 'transcoder/**'

jobs:
  cicd:
    name: build app
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build
        run: |
            cd transcoder   # working dir not persisted
            docker build -t nikhilesh002/vibes-transcoder:latest .

      - name: Build
        run: docker push nikhilesh002/vibes-transcoder:latest